#!/bin/bash

curl -s https://www.reddit.com/r/forhire/.rss \
-A "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0" |\
sed 's/title/\n\n&/g' |\
sed -n 's/\[Hiring\]/\[Hiring\]/p' |\
sed '/^.\{2048\}./d' |\
sed 's/title>\[Hiring\]//g' |\
sed 's/\[Contract\]//g' |\
sed s'/..$/ /'
